name: 'Get & Cache dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  caching:
    type: boolean
    describe: 'Whether to cache the dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install-deps.outputs.cache }} # it gets the value of the install-deps step
runs:
  using: 'composite' # tells GitHub actions this is a composite action
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-deps
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: | 
        npm ci
        echo "cache='${{inputs.caching}}'" >> $GITHUB_OUTPUT
      shell: bash # should be added when creating a composite action with the 'run' property
